In [2]:
import chart_studio.plotly as py
import plotly.graph_objs as go

In [3]:
import chart_studio.plotly as py

In [4]:
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

In [5]:
init_notebook_mode(connected=True)

In [6]:
data = dict(type='choropleth', 
            locations = ['AZ','CA','NY'],
            locationmode = 'USA-states',
            colorscale = 'Greens',
            text = ['Arizona','California','New York'],
            z = [1.0,2.0,3.0],
            colorbar = {'title':'Colorbar Title Goes Here'}
            )

In [7]:
data

{'type': 'choropleth',
 'locations': ['AZ', 'CA', 'NY'],
 'locationmode': 'USA-states',
 'colorscale': 'Greens',
 'text': ['Arizona', 'California', 'New York'],
 'z': [1.0, 2.0, 3.0],
 'colorbar': {'title': 'Colorbar Title Goes Here'}}

In [8]:
layout = dict(geo = {'scope':'usa'})

In [9]:
choromap = go.Figure(data = [data], layout = layout)

In [10]:
iplot(choromap)

In [11]:
import pandas as pd

In [12]:
df = pd.read_csv('/Users/michalbando/Downloads/Różne/IT/Python/Python Data Science & Machine Learning/09-Geographical-Plotting/2011_US_AGRI_Exports')

In [155]:
trace = go.Choropleth(
    colorscale = 'YlOrRd',
    locations = df['CODE'],
    locationmode = 'USA-states',
    z = df['total exports'],
    text = df['text'],
    marker = dict(line = dict(color = 'rgb(255,255,255)', width = 2)),
    colorbar = {'title':'Millions USD'}
)

KeyError: 'total exports'

In [154]:
df.head()

          COUNTRY  GDP (BILLIONS) CODE
0     Afghanistan           21.71  AFG
1         Albania           13.40  ALB
2         Algeria          227.80  DZA
3  American Samoa            0.75  ASM
4         Andorra            4.80  AND

In [28]:
layout = dict(title = '2011 US Agriculture Exports by States',
              geo = dict(scope = 'usa', showlakes = True, lakecolor = 'rgb(85,173,240)'))

In [29]:
layout

{'title': '2011 US Agriculture Exports by States',
 'geo': {'scope': 'usa', 'showlakes': True, 'lakecolor': 'rgb(85,173,240)'}}

In [31]:
choromap2 = go.Figure(data=[trace], layout=layout)

In [32]:
iplot(choromap2)

In [33]:
df = pd.read_csv('/Users/michalbando/Downloads/Różne/IT/Python/Python Data Science & Machine Learning/09-Geographical-Plotting/2014_World_GDP')

In [34]:
df.head()

          COUNTRY  GDP (BILLIONS) CODE
0     Afghanistan           21.71  AFG
1         Albania           13.40  ALB
2         Algeria          227.80  DZA
3  American Samoa            0.75  ASM
4         Andorra            4.80  AND

In [92]:
trace = go.Choropleth(
    colorscale = 'tealrose',
    locations = df['COUNTRY'],
    locationmode = 'country names',
    z = df['GDP (BILLIONS)'],
    text = df['COUNTRY'],
    marker = dict(line = dict(color = 'rgb(255,255,255)', width = 2)),
    colorbar = {'title':'World GDP'}
)

In [149]:
layout = dict(title = '2014 World GDP',  width = 950,
    height = 600,
              geo = dict(showframe = False, 
                         projection = {'type':'natural earth'},     
                         showland = True,
                         landcolor = 'rgb(211, 211, 211)'))

In [150]:
layout

{'title': '2014 World GDP',
 'width': 950,
 'height': 600,
 'geo': {'showframe': False,
  'projection': {'type': 'natural earth'},
  'showland': True,
  'landcolor': 'rgb(211, 211, 211)'}}

In [151]:
choromap2 = go.Figure(data=[trace], layout=layout)

In [152]:
iplot(choromap2)

In [122]:
df['COUNTRY']

0         Afghanistan
1             Albania
2             Algeria
3      American Samoa
4             Andorra
            ...
217    Virgin Islands
218         West Bank
219             Yemen
220            Zambia
221          Zimbabwe
Name: COUNTRY, Length: 222, dtype: object