In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data_path = '/Users/michalbando/Downloads/Różne/IT/Python/Dane/AB_NYC_2019.csv'

In [3]:
df = pd.read_csv(data_path)

Zadanie 1: Szybki przegląd i identyfikacja „dziur”
Wczytaj dane i sprawdź, z czym masz do czynienia.

Wyświetl pierwsze 5 wierszy.

Sprawdź typy danych w kolumnach (df.info()).

Wyzwanie: Oblicz, ile dokładnie brakujących wartości (NaN) znajduje się w każdej kolumnie. Które kolumny są najbardziej „dziurawe”?

In [4]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  object
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

In [6]:
df.isna().sum().sort_values(ascending=False)

last_review                       10052
reviews_per_month                 10052
host_name                            21
name                                 16
id                                    0
host_id                               0
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
calculated_host_listings_count        0
availability_365                      0
dtype: int64

Zadanie 2: Wielkie sprzątanie (Data Cleaning)
Zbiór ten ma braki w nazwach i datach.

Wypełnij brakujące wartości w kolumnach name oraz host_name frazą "Unknown".

W kolumnie reviews_per_month zastąp braki zerem (0), zakładając, że brak danych oznacza po prostu brak recenzji.

Wyzwanie: Usuń z ramki danych wiersze, w których cena (price) wynosi 0 (tak, w tym zbiorze zdarzają się darmowe noclegi, co prawdopodobnie jest błędem).

In [7]:
df[['name','host_name']] = df[['name','host_name']].replace(np.nan,'Unknown')

In [8]:
df['reviews_per_month'] = df['reviews_per_month'].replace(np.nan, 0)

In [9]:
df['price'].sort_values(ascending=True) # nie widze zadnych wartosci, gdzie cena jest rowna 0

25796        0
25634        0
25433        0
25753        0
23161        0
         ...
40433     9999
12342     9999
17692    10000
9151     10000
29238    10000
Name: price, Length: 48895, dtype: int64

Zadanie 3: Filtrowanie „Luksusu”
Czas wyciągnąć konkretne informacje.

Stwórz nową ramkę danych (np. df_expensive), która zawiera tylko oferty z ceną powyżej 500$ za noc.

Wyzwanie: Znajdź wszystkie oferty w dzielnicy (neighbourhood_group) Manhattan, które mają więcej niż 100 recenzji i są dostępne przez cały rok (availability_365 wynosi 365).

In [10]:
df_expensive = df.loc[df['price']>500]

df.loc[(df['neighbourhood_group']=='Manhattan') & (df['availability_365']==365)].sort_values(by='number_of_reviews', ascending=False) #nie znajduje takich rekordow, gdzie wszystkie 3 warunki sa spelnione (Manhattan, Availability_365 = 365, number_of_reviews >100)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
235,60611,SpaHa Studio Monthly Rental,292204,Blanca,Manhattan,East Harlem,40.79163,-73.94573,Entire home/apt,125,28,183,2018-09-29,1.83,2,365
366,103806,BOHEMIAN EAST VILLAGE 2 BED HAVEN,251176,Jason,Manhattan,East Village,40.72577,-73.98745,Entire home/apt,249,5,166,2019-05-27,1.68,2,365
3299,1971540,Sunny Midtown NYC Room,10179999,Joseph,Manhattan,Upper West Side,40.77021,-73.98721,Private room,150,1,157,2019-06-28,2.49,1,365
1605,728498,WEST HARLEM PRIVATE BEDROOM,3779334,Lex And Derek,Manhattan,Harlem,40.80517,-73.95404,Private room,80,1,135,2019-06-22,1.67,1,365
1344,591135,Awesome Place! Amazing Location!!!,1523018,T,Manhattan,SoHo,40.72466,-73.99632,Private room,125,1,132,2019-06-05,1.75,1,365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25883,20686701,IN MINT CONDITION-STUDIOS EAST 44TH/UNITED NAT...,76104209,Rated,Manhattan,Midtown,40.75060,-73.97104,Entire home/apt,176,30,0,NaN,0.00,33,365
25986,20753634,IN MINT CONDITION-STUDIOS EAST 44TH/UNITED NAT...,76104209,Rated,Manhattan,Midtown,40.75070,-73.97086,Entire home/apt,175,30,0,NaN,0.00,33,365
25989,20755049,IN MINT CONDITION-STUDIOS EAST 44TH/UNITED NAT...,76104209,Rated,Manhattan,Midtown,40.75161,-73.97017,Entire home/apt,175,30,0,NaN,0.00,33,365
25992,20755691,IN MINT CONDITION-STUDIOS EAST 44TH/UNITED NAT...,76104209,Rated,Manhattan,Midtown,40.75145,-73.97011,Entire home/apt,175,30,0,NaN,0.00,33,365
48844,36453952,West Village Studio on quiet cobblestone street,115491896,Will,Manhattan,West Village,40.73620,-74.00827,Entire home/apt,205,1,0,NaN,0.00,1,365

In [11]:
df_expensive.loc[(df['neighbourhood_group']=='Manhattan') & (df['number_of_reviews']>100) & (df['availability_365']==365)]

Empty DataFrame
Columns: [id, name, host_id, host_name, neighbourhood_group, neighbourhood, latitude, longitude, room_type, price, minimum_nights, number_of_reviews, last_review, reviews_per_month, calculated_host_listings_count, availability_365]
Index: []

Zadanie 4: Statystyki dzielnic (Grouping)
Dowiedz się, gdzie jest najdrożej.

Pogrupuj dane według neighbourhood_group i oblicz średnią oraz medianę cen w każdej z nich.

Oblicz, ile ofert każdego typu (room_type) znajduje się w całym Nowym Jorku.

Wyzwanie: Sprawdź, która konkretna dzielnica (neighbourhood – to ta mniejsza jednostka, np. Williamsburg) ma najwyższą średnią cenę za cały pokój (Entire home/apt).

In [12]:
df.groupby(by='neighbourhood_group')['price'].agg(['mean','median']).round(2)

                       mean  median
neighbourhood_group
Bronx                 87.50    65.0
Brooklyn             124.38    90.0
Manhattan            196.88   150.0
Queens                99.52    75.0
Staten Island        114.81    75.0

In [ ]:

df.groupby('room_type')['neighbourhood'].agg('count')

room_type
Entire home/apt    25409
Private room       22326
Shared room         1160
Name: neighbourhood, dtype: int64

In [65]:
# # Wyzwanie: Sprawdź, która konkretna dzielnica (neighbourhood – to ta mniejsza jednostka, np. Williamsburg) ma najwyższą średnią cenę za cały pokój (Entire home/apt).
df_filtered = df.loc[df['room_type']=='Entire home/apt']

# df_filtered.groupby('neighbourhood')['price'].mean().round(2).sort_values(ascending=False).head(1)
df_filtered.groupby('neighbourhood')['price'].agg(['mean','count']).sort_values(by='mean',ascending=False)

                      mean  count
neighbourhood
Fort Wadsworth  800.000000      1
Woodrow         700.000000      1
Randall Manor   651.000000      9
Sea Gate        649.400000      5
Tribeca         561.818182    143
...                    ...    ...
Grant City       71.750000      4
Soundview        70.000000      5
Woodlawn         65.500000      4
Emerson Hill     63.500000      2
New Dorp         57.000000      1

[216 rows x 2 columns]

Zadanie 5: Rankingi gospodarzy
Kto trzyma władzę na Airbnb w Nowym Jorku?

Znajdź 10 gospodarzy (host_name lub host_id), którzy mają wystawionych najwięcej ofert.

Wyzwanie: Stwórz nową kolumnę o nazwie revenue_min, która będzie wynikiem pomnożenia price przez minimum_nights. Wyświetl 5 ofert o najwyższym „minimalnym przychodzie”.

In [72]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,0.00,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [141]:
df_host_listings = df[['host_id','host_name','calculated_host_listings_count']].sort_values(by='calculated_host_listings_count', ascending=False)
df_host_listings = df_host_listings.groupby(['host_id','host_name']).size().sort_values(ascending=False).head(10)
df_host_listings = pd.DataFrame(df_host_listings).reset_index()
df_host_listings['offers_counter'] = df_host_listings[0]
df_host_listings.drop(columns=0, inplace=True)
df_host_listings

     host_id          host_name  offers_counter
0  219517861       Sonder (NYC)             327
1  107434423         Blueground             232
2   30283594               Kara             121
3  137358866             Kazuya             103
4   16098958     Jeremy & Laura              96
5   12243051             Sonder              96
6   61391963  Corporate Housing              91
7   22541573                Ken              87
8  200380610            Pranjal              65
9    1475015               Mike              52

In [ ]:
# Wyzwanie: Stwórz nową kolumnę o nazwie revenue_min, która będzie wynikiem pomnożenia price przez minimum_nights. Wyświetl 5 ofert o najwyższym „minimalnym przychodzie”.
df['revenue_min'] = df['price']*df['minimum_nights']
# df['revenue_min'].sort_values(ascending=False).head(5)
df.sort_values(by='revenue_min', ascending=False)[['name', 'host_name', 'revenue_min']].head(5)

                                               name host_name  revenue_min
48043  Luxury TriBeCa Apartment at an amazing price     Jenny      1170000
9151            Furnished room in Astoria apartment  Kathrine      1000000
12342           Quiet, Clean, Lit @ LES & Chinatown       Amy       989901
17811                  Gorgeous 2 Bedroom apartment     Iveta       857750
44429            Room with sofa bed or air mattress    Noelle       730000

1. Porównanie średnich cen zakwaterowania w głównych dzielnicach (Matplotlib)
Cel analizy: Sprawdzenie, jak lokalizacja wpływa na koszt wynajmu. Pytanie badawcze: Czy Manhattan jest faktycznie najdroższym obszarem Nowego Jorku, czy różnica względem Brooklynu jest znikoma?

Wskazówka do wykonania: Wykorzystaj zagregowane dane ze średnią ceną dla każdej z pięciu grup dzielnic (neighbourhood_group).

2. Struktura rynku Airbnb: Rozkład typów pokoi (Matplotlib)
Cel analizy: Zrozumienie, jaki rodzaj zakwaterowania dominuje w ofercie miasta. Pytanie badawcze: Jaki procent ofert stanowią całe apartamenty (Entire home/apt) w porównaniu do tańszych alternatyw, takich jak pokoje prywatne czy współdzielone?

Wskazówka do wykonania: Wyświetl udział procentowy każdego typu pokoju (room_type), co pozwoli ocenić, czy NYC to rynek zorientowany na turystów luksusowych, czy budżetowych.

3. Koncentracja rynku: Top 10 najbardziej aktywnych gospodarzy (Seaborn)
Cel analizy: Identyfikacja kluczowych dostawców usług na platformie. Pytanie badawcze: Czy rynek Airbnb w Nowym Jorku jest rozproszony wśród tysięcy drobnych właścicieli, czy zdominowany przez dużych graczy posiadających setki lokali?

Wskazówka do wykonania: Wykorzystaj przygotowaną wcześniej tabelę z rankingiem gospodarzy (host_name) i liczbą ich ofert (offers_counter).

In [ ]:
from dash import Dash, html, dcc, callback, Output, Input
import plotly.express as px
import pandas as pd

# 1. Przygotowanie danych (wykorzystujemy Twoje przefiltrowane dane)
df = pd.read_csv('../Dane/AB_NYC_2019.csv')

# Inicjalizacja aplikacji Dash dla Jupytera
app = Dash(__name__)

# 2. Layout - Co widzimy na ekranie
app.layout = html.Div([
    html.H2("Analiza cen Airbnb w Nowym Jorku"),

    html.Label("Wybierz grupę dzielnic:"),
    dcc.Dropdown(
        options=df['neighbourhood_group'].unique(),
        value='Manhattan', # Wartość startowa
        id='dropdown-selection'
    ),

    dcc.Graph(id='graph-content')
])

# 3. Callback - Logika interakcji (Serce Dasha)
@callback(
    Output('graph-content', 'figure'),
    Input('dropdown-selection', 'value')
)
def update_graph(selected_group):
    # Filtrowanie danych na żywo
    filtered_df = df[df['neighbourhood_group'] == selected_group]

    # Tworzenie wykresu w Plotly
    fig = px.histogram(
        filtered_df,
        x='neighbourhood',
        y='price',
        histfunc='avg',
        title=f'Średnie ceny w: {selected_group}',
        labels={'price': 'Średnia Cena ($)', 'neighbourhood': 'Okolica'}
    ).update_xaxes(categoryorder='total descending')

    return fig

# 4. Uruchomienie wewnątrz notatnika
if __name__ == '__main__':
    app.run(jupyter_mode="inline") # To sprawi, że Dash pojawi się pod komórką