<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="300" alt="Skills Network Logo">
    </a>
</p>

# Practice Project: GDP Data extraction and processing

Estimated time needed: **30** minutes

## Introduction

In this practice project, you will put the skills acquired through the course to use. You will extract data from a website using webscraping and reqeust APIs process it using Pandas and Numpy libraries.

## Project Scenario:

An international firm that is looking to expand its business in different countries across the world has recruited you. You have been hired as a junior Data Engineer and are tasked with creating a script that can extract the list of the top 10 largest economies of the world in descending order of their GDPs in Billion USD (rounded to 2 decimal places), as logged by the International Monetary Fund (IMF). 

The required data seems to be available on the URL mentioned below:

URL: https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29

## Objectives

After completing this lab you will be able to:

 - Use Pandas to read the data from html page and process the tabular data as a dataframe.
 - Use Numpy to manipulate the information contatined in the dataframe.
 - Load the updated dataframe to CSV file.

---

## Dislcaimer

If you are using a downloaded version of this notebook on your local machine, you may encounter a warning message as shown in the screenshot below.

<p style="text-align:center">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/mod_5/practice_project_disclaimer.png" width="700" alt="warning message">
</p>


This does not affect the execution of your codes in any way and can be simply ignored.

# Setup

For this lab, we will be using the following libraries:

*   [`pandas`](https://pandas.pydata.org/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0187ENSkillsNetwork31430127-2021-01-01) for managing the data.
*   [`numpy`](https://numpy.org/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0187ENSkillsNetwork31430127-2021-01-01) for mathematical operations.

### Importing Required Libraries

_We recommend you import all required libraries in one place (here):_

In [1]:
import numpy as np
import pandas as pd

# You can also use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

/Users/michalbando/anaconda3/lib/python3.10/site-packages/pandas/core/arrays/masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

---

# Exercises

### Exercise 1
Extract the required GDP data from the given URL using Web Scraping.

In [2]:
URL="https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29"

You can use Pandas library to extract the required table directly as a DataFrame. Note that the required table is the third one on the website, as shown in the image below.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/images/pandas_wbs_3.png">

In [44]:
# Extract tables from webpage using Pandas. Retain table number 3 as the required dataframe.
tables = pd.read_html(URL)
df = tables[3]
# Replace the column headers with column numbers
df.columns = range(df.shape[1])

# Retain columns with index 0 and 2 (name of country and value of GDP quoted by IMF)
df_shorter = df[[0,2]]
df_shorter = df_shorter.iloc[0:10]# Retain the Rows with index 1 to 10, indicating the top 10 economies of the world.
# Assign column names as "Country" and "GDP (Million USD)"
df_shorter.columns = ['Country','GDP (Million USD)']
df_shorter

          Country GDP (Million USD)
0           World         105568776
1   United States          26854599
2           China          19373586
3           Japan           4409738
4         Germany           4308854
5           India           3736882
6  United Kingdom           3158938
7          France           2923489
8           Italy           2169745
9          Canada           2089672

<details>
    <summary>Click here for Solution</summary>

```python
# Extract tables from webpage using Pandas. Retain table number 3 as the required dataframe.
tables = pd.read_html(URL)
df = tables[3]

# Replace the column headers with column numbers
df.columns = range(df.shape[1])

# Retain columns with index 0 and 2 (name of country and value of GDP quoted by IMF)
df = df[[0,2]]

# Retain the Rows with index 1 to 10, indicating the top 10 economies of the world.
df = df.iloc[1:11,:]

# Assign column names as "Country" and "GDP (Million USD)"
df.columns = ['Country','GDP (Million USD)']
```

</details>

### Exercise 2
Modify the GDP column of the DataFrame, converting the value available in Million USD to Billion USD. Use the `round()` method of Numpy library to round the value to 2 decimal places. Modify the header of the DataFrame to `GDP (Billion USD)`.

In [45]:
# Change the data type of the 'GDP (Million USD)' column to integer. Use astype() method.
df_shorter['GDP (Million USD)'] = df_shorter['GDP (Million USD)'].astype('int64')
# Convert the GDP value in Million USD to Billion USD
df_shorter['GDP (Million USD)'] = df_shorter['GDP (Million USD)']*0.001
# Use numpy.round() method to round the value to 2 decimal places.
df_shorter.head()
# Rename the column header from 'GDP (Million USD)' to 'GDP (Billion USD)'

         Country  GDP (Million USD)
0          World         105568.776
1  United States          26854.599
2          China          19373.586
3          Japan           4409.738
4        Germany           4308.854

In [50]:
df_shorter['GDP (Billion USD)'] = np.round(df_shorter['GDP (Billion USD)'], 2)

df_shorter.columns=('Country','GDP (Billion USD)')
df_shorter

          Country  GDP (Billion USD)
0           World          105568.78
1   United States           26854.60
2           China           19373.59
3           Japan            4409.74
4         Germany            4308.85
5           India            3736.88
6  United Kingdom            3158.94
7          France            2923.49
8           Italy            2169.74
9          Canada            2089.67

<details>
    <summary>Click here for solution</summary>
    
```python
# Change the data type of the 'GDP (Million USD)' column to integer. Use astype() method.
df['GDP (Million USD)'] = df['GDP (Million USD)'].astype(int)

# Convert the GDP value in Million USD to Billion USD
df[['GDP (Million USD)']] = df[['GDP (Million USD)']]/1000

# Use numpy.round() method to round the value to 2 decimal places.
df[['GDP (Million USD)']] = np.round(df[['GDP (Million USD)']], 2)

# Rename the column header from 'GDP (Million USD)' to 'GDP (Billion USD)'
df.rename(columns = {'GDP (Million USD)' : 'GDP (Billion USD)'})

```
</details>

### Exercise 3

Load the DataFrame to the CSV file named "Largest_economies.csv"

In [51]:
# Load the DataFrame to the CSV file named "Largest_economies.csv"
df1 = pd.read_csv('./Largest_economies.csv')

FileNotFoundError: [Errno 2] No such file or directory: './Largest_economies.csv'

<details>
    <summary>Click here for Solution</summary>

```python
# Load the DataFrame to the CSV file named "Largest_economies.csv"
df.to_csv('./Largest_economies.csv')
```

</details>

---

# Congratulations! You have completed the lab.

## Authors

[Abhishek Gagneja](https://www.linkedin.com/in/abhishek-gagneja-23051987/)

## Change Log

|Date (YYYY-MM-DD)|Version|Changed By|Change Description|
|-|-|-|-|
|2023-11-10|0.1|Abhishek Gagneja|Created initial version|

Copyright © 2023 IBM Corporation. All rights reserved.