In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data_path = '/Users/michalbando/Downloads/Różne/IT/IBM Data Analyst Professional/Python/ChicagoCensusData.csv'
df = pd.read_csv(data_path)

df.head()

,COMMUNITY_AREA_NUMBER,COMMUNITY_AREA_NAME,PERCENT_OF_HOUSING_CROWDED,PERCENT_HOUSEHOLDS_BELOW_POVERTY,PERCENT_AGED_16__UNEMPLOYED,PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA,PERCENT_AGED_UNDER_18_OR_OVER_64,PER_CAPITA_INCOME,HARDSHIP_INDEX
0,1.0,Rogers Park,7.7,23.6,8.7,18.2,27.5,23939,39.0
1,2.0,West Ridge,7.8,17.2,8.8,20.8,38.5,23040,46.0
2,3.0,Uptown,3.8,24.0,8.9,11.8,22.2,35787,20.0
3,4.0,Lincoln Square,3.4,10.9,8.2,13.4,25.5,37524,17.0
4,5.0,North Center,0.3,7.5,5.2,4.5,26.2,57123,6.0

In [4]:
df.columns

Index(['COMMUNITY_AREA_NUMBER', 'COMMUNITY_AREA_NAME',
       'PERCENT_OF_HOUSING_CROWDED', 'PERCENT_HOUSEHOLDS_BELOW_POVERTY',
       'PERCENT_AGED_16__UNEMPLOYED',
       'PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA',
       'PERCENT_AGED_UNDER_18_OR_OVER_64', 'PER_CAPITA_INCOME',
       'HARDSHIP_INDEX'],
      dtype='object')

In [6]:
df[['COMMUNITY_AREA_NUMBER','COMMUNITY_AREA_NAME']]

    COMMUNITY_AREA_NUMBER COMMUNITY_AREA_NAME
0                     1.0         Rogers Park
1                     2.0          West Ridge
2                     3.0              Uptown
3                     4.0      Lincoln Square
4                     5.0        North Center
..                    ...                 ...
73                   74.0     Mount Greenwood
74                   75.0         Morgan Park
75                   76.0              O'Hare
76                   77.0           Edgewater
77                    NaN             CHICAGO

[78 rows x 2 columns]